language: node_js
node_js:
 - "10"
cache:
  directories:
    - "node_modules"
global:
  - CODECLIMATE_REPO_TOKEN=d2743ffa22c21c3a7225a0331886c388e82e98a36f5854d127575b16ff41f4c7
install:
  - npm install
script: "npm test"
after_success:
  - npm run coverage
  