language: node_js
node_js:
 - "12"
cache:
  directories:
    - "node_modules"
global:
  - CODECLIMATE_REPO_TOKEN=70a5fa8474a0927e9fd5026fd87b9be8ced203b2d716ea0baee00503e7c643d0
install:
  - npm install
script: "npm test"
after_success:
  - npm run coverage
  